### ISSUE TITLE
Skip grouping

### ISSUE THREAD

**Issue by breese** [jefftrull/gdb_python_api#1]
This is a feature request.

If I set `backtrace-skip-regex` to `^(std::|boost::)` it will collapse both std and boost into one group.

It would be nice if I could get more groups instead, such that one only collapses `std::` and the other `boost::`. Eventually I would also like to group individual boost namespaces.

**Comment by jefftrull** [comment]
This is a great idea. I don't know when I'll be able to work on it, but I agree 100%.

**Comment by jefftrull** [comment]
What if I introduced a new parameter called `backtrace-skip-regexes` that had special interpretation of regex groups so you could set it to `(^std::)|(^boost::)` and each regex group would be considered a different kind of match? That should be straightforward.

**Comment by jefftrull** [comment]
I just implemented the feature described above, in https://github.com/jefftrull/gdb_python_api/commit/869046b6f0c50d24b784a67edaf94afacf822fec

Accordingly I think this issue is now fixed.
