### ISSUE TITLE
Stepu fails

### ISSUE THREAD

**Issue by ghamarian** [jefftrull/gdb_python_api#6]
Here is the error I get:
```
Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'filename':
Error occurred in Python: 'NoneType' object has no attribute 'filename'
```

This is how I compiled it. I use clang 14.
```
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=/usr/bin/make  -DCMAKE_TOOLCHAIN_FILE=/home/oem/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake -G "CodeBlocks - Unix Makefiles" -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++  -S. -B build -DCMAKE_EXPO```

**Comment by jefftrull** [comment]
Hi! Thanks for the bug report. Can you also supply the program you are trying to debug, and its build instructions? I'll need that in order to reproduce.

**Comment by jefftrull** [comment]
And your Python version - thanks.

**Comment by jefftrull** [comment]
Without a [minimal working example](https://en.wikipedia.org/wiki/Minimal_reproducible_example#:~:text=A%20minimal%20reproducible%20example%20may,short%20self%2Dcontained%20correct%20example.) there is no way I can reproduce this error. Please give me this additional information so I can help you. Thanks.

**Comment by jefftrull** [comment]
Requested information not provided; closing ticket.
